name: isolate_sqlite
description: Run an SQLite database in the isolate the easy way.
version: 0.0.1
repository: https://github.com/claudare/isolate_sqlite
license: MIT

environment:
  sdk: ^3.11.3

# Add regular dependencies here.
dependencies:
  sqlite3: ^3.2.0
  # path: ^1.9.0

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.25.6
